lecture_4/airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("flights/", include("flights.urls")),
]

lecture_4/airline/flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

lecture_4/airline/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout")
]

lecture_4/airline/flights/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"


class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

lecture_4/airline/users/models.py
from django.db import models

# Create your models here.

lecture_4/airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Flight, Passenger
# Create your views here.

namespace = "flights"

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })
    
def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST.get("passenger")))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight_id,)))

lecture_4/airline/users/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import redirect
# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    return render(request, "users/user.html", {
        "user": User.objects.get(pk=request.user.id)
    })


def login_request(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            print("User authenticated")
            login(request, user)
            return HttpResponseRedirect(reverse("users:index")) 

        return render(request, "users/login.html", {
            "message": "Invalid credentials"
        })
    
    return render(request, "users/login.html")

def logout_request(request):
    logout(request)
    return render(request, "users/login.html",{
        "message": "You have been logged out"
    })

lecture_4/airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flight {{ flight.id }}</h1>
<p>Departure: {{ flight.origin }}</p>
<p>Destination: {{ flight.destination }}</p>
<p>Duration: {{ flight.duration }}</p>

<h2>Passengers</h2>
{% if passengers %}
<ul>
    {% for passenger in passengers %}
    <li>{{ passenger.first }} {{ passenger.last }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No passengers.</p>
{% endif %}

<a href="{% url 'flights:index' %}">Back to flights</a>

<h2>Add Passengers</h2>
<form action="{% url 'flights:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="passenger">
        {% for passenger in non_passengers %}
        <option value="{{ passenger.id }}">{{ passenger.first }} {{ passenger.last }}</option>
        {% endfor %}
    </select>
    <button type="submit">Book</button>
</form>
{% endblock %}

lecture_4/airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flights</h1>
<ul>
    {% for flight in flights %}
    <a href="{% url 'flights:flight' flight.id %}">
        <li>Flight {{ flight.id }}: {{ flight.origin }} to {{ flight.destination }}</li>
    </a>
    {% endfor %}
</ul>
{% endblock %}

lecture_4/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <h1>Flights</h1>
    {% block body %}{% endblock %}
</body>

</html>

lecture_4/airline/users/templates/users/index.html
{% extends "users/layout.html" %}

{% block content %}
<h1>Users</h1>
<ul>
    {% for user in users %}
    <li>{{ user.username }}</li>
    {% endfor %}
</ul>
{% endblock %}

lecture_4/airline/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>

    </header>
    <main>
        {% block content %}{% endblock %}
    </main>

</body>

</html>

lecture_4/airline/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block content %}

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="username" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <button type="submit">Login</button>
</form>
{% endblock %}

lecture_4/airline/users/templates/users/user.html
{% extends "users/layout.html" %}

{% block content %}

<a href="{% url 'users:logout' %}">Logout</a>
<h1>Welcome {{ request.user.first_name }}</h1>

<ul>
    <li>Username: {{ request.user.username }}</li>
    <li>Email: {{ request.user.email }}</li>
    <li>First Name: {{ request.user.first_name }}</li>
    <li>Last Name: {{ request.user.last_name }}</li>
</ul>
{% endblock %}