wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.article, name="article"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("random", views.random_article, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from encyclopedia import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

handler404 = views.error_404

wiki/encyclopedia/views.py
import markdown
import random
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from . import util

class NewTaskForm(forms.Form):
    title = forms.CharField(label="Article")
    edit = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    content = forms.CharField(widget=forms.Textarea, label="markdown content")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def error_404(request, exception):
    return render(request, "encyclopedia/error.html", status=404)
    
def article(request, title):
    if request.method == "POST":
        return render(request, "encyclopedia/new.html", {
                 "form": NewTaskForm(
                    initial={
                        'title': title,
                        'edit': True,
                        'content': util.get_entry(title)
                    }
                 )
                })
    
    content = util.get_entry(title)
    if not content:
        return render(request, "encyclopedia/article.html", {
            "title": title.title(),
            "error": "Article does not exist"
        })
    return render(request, "encyclopedia/article.html", {
        "title": title.title(),
        "content": markdown.markdown(content)
    })

def random_article(request):
    random_choice = random.choice(util.list_entries())
    return render(request, "encyclopedia/article.html", {
        "title": random_choice.title(),
        "content": markdown.markdown(util.get_entry(random_choice))
    })

def search(request):
    query = request.GET.get('q', '')
    if util.get_entry(query):
        return render(request, "encyclopedia/article.html", {
            "title": query.title(),
            "content": markdown.markdown(util.get_entry(query))
        })

    possible_entries = []
    for entry in util.list_entries():
        if query.lower() in entry.lower():
            possible_entries.append(entry)
    return render(request, "encyclopedia/search.html", {
        "entries": possible_entries
    })

def new(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            edit = form.cleaned_data["edit"]
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if not content.lower().startswith(f"# {title.lower()}"):
                content = f"# {title.title()}\n\n" + content
            if not util.get_entry(title) or edit:
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:article", args=[title]))
            else:
                return render(request, "encyclopedia/new.html", {
                "error": "Error: Article already exists"
            })
    return render(request, "encyclopedia/new.html", {
       "form": NewTaskForm()
    })

wiki/encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
{% if not error %}
<form action="{% url 'encyclopedia:article' title %}" method="post">
    {% csrf_token %}
    <button type="submit">Edit</button>
</form>
{% endif %}
{% if content %}
{{ content|safe }}

{% else %}
<h1>{{ error }}</h1>
{% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
<div class="error-page">
    <h1> :(</h1>
    <h2>The web page you are looking for does not exist</h2>
    <a href="{% url 'encyclopedia:index' %}">Return to the homepage</a>
</div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li>{{ entry }}</li>
    {% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                <button type="submit">Search</button>
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}

{% endblock %}

{% block body %}

{% if error %}
<p>{{ error }}</p>
{% else %}
<div class="main-form">
    <form action="{% url 'encyclopedia:new' %}" method="post">
        {% csrf_token %}

        <div class="form-row">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>

        {{ form.edit }}

        <div class="form-row">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>

        <button type="submit">Save Article</button>
    </form>
</div>
{% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
{% if content %}
<div class="markdown-container">
    {{ content|safe }}
</div>
{% elif entries %}
<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'encyclopedia:article' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<h3>:( Could not find any results for your search.</h3>
{% endif %}

{% endblock %}