commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("comment/<int:listing_id>", views.comment, name="comment"),
    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("category/<int:category_id>", views.category, name="category")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

    def __str__(self):
        return f"{self.username}"

class Category (models.Model):
    name = models.CharField(max_length=64)
    
    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    lowest_bid = models.DecimalField(decimal_places=2, max_digits=10)
    actual_bid = models.DecimalField(decimal_places=2, max_digits=10,default=0)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="winner", null=True,blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category")
    image = models.URLField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    enabled = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.title}"

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bidder")
    bid_amount =  models.DecimalField(decimal_places=2, max_digits=10)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.bidder} bid {self.bid_amount} on {self.date}"


class Comment(models.Model):
    comenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comenter")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()

    def __str__(self):
        return f"{self.comenter} commented {self.comment} on {self.listing}"


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} is watching {self.listing}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.contrib import messages
import decimal

from .models import User, Category, Listing, Watchlist, Bid, Comment

class NewTaskForm(forms.Form):
    title = forms.CharField(label="Product Name")
    description = forms.CharField(label="Description")
    lowest_bid = forms.DecimalField(label="Lowest Bid")
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label="Categories")
    image = forms.URLField(label="Image URL")

class NewBidForm(forms.Form):
    bid = forms.DecimalField(label="Bid")

class NewCommentForm(forms.Form):
    comment = forms.CharField(label="Your comment")

def index(request):
    if request.user.is_authenticated:
        return render(request, "auctions/index.html",{
            "listings": Listing.objects.exclude(owner=request.user).all(),
            "my_listings": Listing.objects.filter(owner=request.user).all()
        })
    return render(request, "auctions/index.html",{
        "listings": Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        
        if not username or not email or not password or not confirmation:
            return render(request, "auctions/register.html", {
                "message": "Username, email, password and confirmation are required."
            })


        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

def create(request):
    
    if request.method == "POST" and request.user.is_authenticated:
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = request.POST["title"]
            description = request.POST["description"]
            lowest_bid = request.POST["lowest_bid"]
            category = request.POST["category"]
            image = request.POST["image"]
            owner = request.user 
            listing = Listing(title=title, description=description, lowest_bid=lowest_bid, category_id=category, image=image, owner=owner)
            listing.save()
            return HttpResponseRedirect(reverse("auctions:index"))
    return render(request, "auctions/create.html",
    {"form": NewTaskForm()
    })


def listing(request, listing_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            action = request.POST.get("action")
            if action == "add":
                watchlist = Watchlist(user=request.user, listing_id=listing_id)
                watchlist.save()
            elif action == "remove":
                watchlist = Watchlist.objects.filter(user=request.user, listing_id=listing_id)
                watchlist.delete()
            elif action == "bid":
                form = NewBidForm(request.POST)
                if form.is_valid():
                    bid_amount = form.cleaned_data["bid"]
                    listing = Listing.objects.get(id=listing_id)
                    if bid_amount > listing.actual_bid and bid_amount >= listing.lowest_bid:
                        bid = Bid(bidder=request.user, bid_amount=bid_amount, listing_id=listing_id)
                        bid.save()
                        listing.actual_bid = bid.bid_amount
                        listing.save()
                    else:
                        messages.error(request, "Your bid must be higher than the current bid.")
            elif action == "close":
                
                    listing = Listing.objects.get(id=listing_id)
                    listing.enabled = False
                    highest_bid = Bid.objects.filter(listing_id=listing_id).order_by("-bid_amount").first()
                    listing.winner = highest_bid.bidder if highest_bid else None
                    listing.save()
                    return HttpResponseRedirect(reverse("auctions:index"))
        is_in_watchlist = Watchlist.objects.filter(user=request.user, listing_id=listing_id).exists()
        comments = Comment.objects.filter(listing_id=listing_id)
        return render(request, "auctions/listing.html", {
            "listing": Listing.objects.get(id=listing_id),
            "bid_form": NewBidForm(),
            "is_in_watchlist": is_in_watchlist,
            "comment_form": NewCommentForm(),
            "comments": comments
        })
    else:
        return render(request, "auctions/listing.html", {
            "error": "You must be logged in to view this page.",
        })

def comment(request, listing_id):
    if request.method == "POST":
        form = NewCommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data["comment"]
            listing = Listing.objects.get(id=listing_id)
            comment = Comment(comenter=request.user, listing=listing, comment=comment)
            comment.save()
            return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))

def watchlist(request):
    if request.user.is_authenticated:
        watchlist = Watchlist.objects.filter(user=request.user)
        listings = Listing.objects.filter(id__in=watchlist.values("listing_id"))
        return render(request, "auctions/watchlist.html", {
            "listings": listings
        })
    return render(request, "auctions/watchlist.html")   

def category(request, category_id):
        listings = Listing.objects.filter(category_id=category_id)
        return render(request, "auctions/category.html", {
            "listings": listings
        })

def categories(request):
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {
        "categories": categories
    })

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}

{%if categories %}
<ul>
    {%for category in categories%}
    <li>
        <a href="{% url 'auctions:category' category.id %}">{{ category.name }}</a>
    </li>
    {% endfor%}
</ul>
{%else%}
<p>No categories found.</p>
{% endif %}
{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% block body %}
<div class="category-list">
    {% if listings %}
    {% for listing in listings %}
    <div class="auction-card position-relative">
        <div class="auction-card-image">
            <img src="{{ listing.image }}" alt="{{ listing.title }}">
        </div>

        <div class="auction-card-content">
            <h3>{{ listing.title }}</h3>
            <p>{{ listing.description }}</p>
            <p>Price: <strong>${{ listing.lowest_bid }}</strong></p>
            <a href="{% url 'auctions:listing' listing.id %}" class="stretched-link">View Listing</a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No items in this category.</p>
    {% endif %}
</div>
{% endblock %}

commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if user.is_authenticated %}
<form action="{% url 'auctions:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Listing</button>
</form>
{% else %}
<p>Please log in to create a listing.</p>
{% endif %}
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>
{% for listing in listings %}
{% if listing.enabled %}
<div class="auction-card position-relative">
    <div class="auction-card-image">
        <img src="{{ listing.image }}" alt="{{ listing.title }}">
    </div>

    <div class="auction-card-content">
        <h3>{{ listing.title }}</h3>
        <p>{{ listing.description }}</p>
        <p>Price: <strong>${{ listing.lowest_bid }}</strong></p>
        <a href="{% url 'auctions:listing' listing.id %}" class="stretched-link">View Listing</a>
    </div>
</div>
{% endif %}
{% endfor %}

<h2>Won Listings</h2>
{% for listing in listings %}
{% if not listing.enabled and listing.winner == request.user %}
<div class="auction-card position-relative">
    <div class="auction-card-image">
        <img src="{{ listing.image }}" alt="{{ listing.title }}">
    </div>

    <div class="auction-card-content">
        <h3>{{ listing.title }}</h3>
        <p>{{ listing.description }}</p>
        <p>Price: <strong>${{ listing.lowest_bid }}</strong></p>
        <p>You won this listing for ${{ listing.actual_bid }}</p>
        <a href="{% url 'auctions:listing' listing.id %}" class="stretched-link">View Listing</a>
    </div>
</div>
{% endif %}
{% endfor %}


{% if request.user.is_authenticated %}
<h2>My Listings</h2>
{% if my_listings %}
{% for listing in my_listings %}
<div class="auction-card position-relative">
    <div class="auction-card-image">
        <img src="{{ listing.image }}" alt="{{ listing.title }}">
    </div>

    <div class="auction-card-content">
        <h3>{{ listing.title }}</h3>
        <p>{{ listing.description }}</p>
        <p>Price: <strong>${{ listing.lowest_bid }}</strong></p>
        {% if listing.enabled %}
        <a href="{% url 'auctions:listing' listing.id %}" class="stretched-link">View Listing</a>
        {% else %}
        <p>You closed this listing.</p>
        <p>the winner is {{ listing.winner }} for ${{ listing.actual_bid }}</p>
        {% endif %}
    </div>
</div>
{% endfor %}
{% else %}
<p>Begin and add a new listing.</p>
<a href="{% url 'auctions:create' %}">Create Listing</a>
{% endif %}
{% else %}
<p>Please log in to see your listings.</p>
{% endif %}
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
</head>

<body>

    <h1>Auctions</h1>
    <div>
        {% if user.is_authenticated %}
        Signed in as <strong>{{ user.username }}</strong>.
        {% else %}
        Not signed in.
        {% endif %}
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:create'%}">Create Listing</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:categories' %}">Categories </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
        </li>
        {% endif %}
    </ul>
    <hr>
    <div class="container mt-2">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if error %}
<p>{{ error }}</p>
{% else %}
{% if request.user.is_authenticated and listing.enabled %}
<div class="auction-card-center">
    <div class="auction-card-image">
        <img src="{{ listing.image }}" alt="{{ listing.title }}">
    </div>
    <h2>{{ listing.title }}</h2>
    <p>{{ listing.description }}</p>
    <p>Category: <strong>{{ listing.category }}</strong></p>
    <p>Initial Price: <strong>${{ listing.lowest_bid }}</strong></p>
    <p>Actual Bid: <strong>${{ listing.actual_bid }}</strong></p>

    {% if request.user.is_authenticated and request.user != listing.owner %}
    {% if is_in_watchlist %}
    <form action="{% url 'auctions:listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="remove">
        <button type="submit" class="btn btn-secondary mt-2 w-100">Remove from watchlist</button>
    </form>
    {% else %}
    <form action="{% url 'auctions:listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="add">
        <button type="submit" class="btn btn-secondary mt-2 w-100">Add to watchlist</button>
    </form>
    {% endif %}
    <hr>
    <form action="{% url 'auctions:listing' listing.id %}" method="post">
        {% csrf_token %}
        {{ bid_form }}
        <input type="hidden" name="action" value="bid">
        <button class="btn btn-primary mt-2 w-100" type="submit">Bid now</button>
    </form>
    {% endif %}
    {% if request.user.is_authenticated and request.user == listing.owner %}
    <form action="{% url 'auctions:listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="close">
        <button type="submit" class="btn btn-danger mt-2 w-100">Close Listing</button>
    </form>
    {% endif %}
</div>
{%elif request.user.is_authenticated and listing.enabled == False and listing.winner == request.user %}
<div class="auction-card-center">
    <div class="auction-card-image">
        <img src="{{ listing.image }}" alt="{{ listing.title }}">
    </div>
    <h2>{{ listing.title }}</h2>
    <p>{{ listing.description }}</p>
    <p>Category: <strong>{{ listing.category }}</strong></p>
    <p>Initial Price: <strong>${{ listing.lowest_bid }}</strong></p>
    <p>Actual Bid: <strong>${{ listing.actual_bid }}</strong></p>
    <p>You won this listing for ${{ listing.actual_bid }}</p>
</div>
{% else %}
<p>This listing is not available anymore.</p>
{% endif %}
</div class="comments mt-4">
<h2>Comments</h2>
{% if request.user.is_authenticated %}
<div class="card mb-4">
    <div class="card-body">
        <form action="{% url 'auctions:comment' listing.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ comment_form }}
            </div>
            <button class="btn btn-primary mt-2 w-20" type="submit">Comment</button>
        </form>
    </div>
</div>
{% endif %}
<div class="comments-list">
    {% for comment in comments %}
    <div class="auction-comment">
        <div class="comment-header">
            <span class="comment-user"><strong>@{{ comment.comenter }}</strong></span>
        </div>
        <div class="comment-body">
            {{ comment.comment }}
        </div>
    </div>
    {% empty %}
    <p class="text-muted">Nothing here. Help us comment!</p>
    {% endfor %}
</div>
</div>
{% endif %}
{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'auctions:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'auctions:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% block body %}
{% if request.user.is_authenticated %}
<div class="watchlist-list">
    {% if listings %}
    {% for listing in listings %}
    <div class="auction-card position-relative">
        <div class="auction-card-image">
            <img src="{{ listing.image }}" alt="{{ listing.title }}">
        </div>

        <div class="auction-card-content">
            <h3>{{ listing.title }}</h3>
            <p>{{ listing.description }}</p>
            <p>Price: <strong>${{ listing.lowest_bid }}</strong></p>
            <a href="{% url 'auctions:listing' listing.id %}" class="stretched-link">View Listing</a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No items in your watchlist.</p>
    {% endif %}
</div>
{% else %}
<p>You are not logged in .</p>
{% endif %}
{% endblock %}